[project]
name = "dbb-rate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "pymongo>=4.14.1",
    "streamlit>=1.49.1",
]
